# Generated by Django 4.2.16 on 2024-11-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(fields=('tenant', 'property', 'start_date', 'end_date'), name='unique_lease_per_tenant'),
        ),
    ]
